use std::{path::PathBuf, sync::Arc};

use ipnetwork::IpNetwork;
use tokio::{fs, io::AsyncWriteExt};
use tracing::{info, warn};
use zerovpn_db::{
    PgPool,
    repos::{devices, servers},
};
use zerovpn_wg::{ip_alloc::IpAllocator, keys};

use crate::state::IpAllocators;

/// Ensure at least one server row exists. If none, create a default one with
/// a freshly-generated WG keypair, an endpoint pointing at
/// `$ZEROVPN_WG__SERVER_ENDPOINT`, and a CIDR of `10.10.0.0/22` (1022 usable
/// hosts, fits 1000+ peers). Also writes `wg0.conf` to the shared
/// `wg_config` volume so the WG container can bring the interface up.
pub async fn ensure_default_server(pool: &PgPool) -> anyhow::Result<()> {
    if servers::count(pool).await? > 0 {
        return Ok(());
    }
    info!("no servers found; creating default");

    let private_key = keys::generate_private_key();
    let public_key = keys::derive_public_key(&private_key)?;

    let endpoint_host = std::env::var("ZEROVPN_WG__SERVER_ENDPOINT")
        .unwrap_or_else(|_| "localhost".to_string());
    let listen_port: i32 = std::env::var("ZEROVPN_WG__LISTEN_PORT")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(51820);

    let cidr: IpNetwork = "10.10.0.0/22".parse().unwrap();
    let dns: IpNetwork = "10.10.0.1/32".parse().unwrap();

    let id = servers::create(
        pool,
        servers::NewServer {
            name: "default",
            region: "local",
            endpoint_host: &endpoint_host,
            endpoint_port: listen_port,
            public_key: &public_key,
            cidr,
            dns_servers: vec![dns],
            mtu: 1420,
        },
    )
    .await?;

    // Write wg0.conf to the shared volume so the wg container has the
    // server keypair on first boot. The path is configurable so it can
    // match wherever the wg image expects to read its config from.
    let conf_path: PathBuf = std::env::var("ZEROVPN_WG__SERVER_CONFIG_PATH")
        .unwrap_or_else(|_| "/wg/wg0.conf".to_string())
        .into();
    let interface = std::env::var("ZEROVPN_WG__INTERFACE").unwrap_or_else(|_| "wg0".into());
    let server_address = "10.10.0.1/22";

    let conf = format!(
        "# Auto-generated by zerovpn-api on first boot. Re-deleting this\n\
         # server row in DB will trigger a regeneration on next start.\n\
         [Interface]\n\
         PrivateKey = {private_key}\n\
         Address = {server_address}\n\
         ListenPort = {listen_port}\n\
         SaveConfig = false\n\
         PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE\n\
         PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE\n",
    );

    if let Some(parent) = conf_path.parent() {
        if let Err(e) = fs::create_dir_all(parent).await {
            warn!(?e, parent = %parent.display(), "could not create wg config dir");
        }
    }
    match fs::File::create(&conf_path).await {
        Ok(mut f) => {
            if let Err(e) = f.write_all(conf.as_bytes()).await {
                warn!(?e, path = %conf_path.display(), "wg0.conf write failed");
            } else {
                let _ = f.sync_all().await;
                info!(server_id = %id, interface, path = %conf_path.display(), "wg0.conf written");
            }
        }
        Err(e) => {
            // Likely the volume isn't mounted (e.g., dev demo without WG
            // container). Log + continue; api still works for the rest of
            // the stack and ShellController will be a no-op anyway.
            warn!(
                ?e,
                path = %conf_path.display(),
                "could not write wg0.conf — WG container will need it injected manually"
            );
        }
    }

    info!(server_id = %id, public_key = %public_key, "default server created");
    Ok(())
}

/// Build per-server IP allocators from the DB on startup.
pub async fn build_ip_allocators(pool: &PgPool) -> anyhow::Result<Arc<IpAllocators>> {
    let allocators = Arc::new(IpAllocators::default());
    for s in servers::list_active(pool).await? {
        let net = match s.cidr {
            IpNetwork::V4(v4) => v4,
            IpNetwork::V6(_) => {
                warn!(server_id = %s.id, "IPv6 CIDR not yet supported by allocator; skipping");
                continue;
            }
        };
        let alloc = Arc::new(IpAllocator::new(net));
        for ip in devices::allocated_ips_for_server(pool, s.id).await? {
            if let std::net::IpAddr::V4(v4) = ip {
                if let Err(e) = alloc.mark_allocated(v4) {
                    warn!(server_id = %s.id, ip = %v4, err = ?e, "failed to seed allocator");
                }
            }
        }
        allocators.insert(s.id, alloc);
    }
    info!(servers = allocators.map.read().len(), "ip allocators built");
    Ok(allocators)
}
