-- ZeroVPN initial schema (Phase 1A)
--
-- Naming: snake_case. Timestamps in TIMESTAMPTZ. UUIDs as v7 (time-ordered)
-- generated by the application; we do not call gen_random_uuid() in DDL so
-- the wire IDs stay sortable.
--
-- Privacy: IPs that we capture are stored as INET prefixes (/24 for IPv4,
-- /48 for IPv6). User agents are sha256-hashed. No DNS query logs, no
-- destination IP logs, no traffic content anywhere.

CREATE EXTENSION IF NOT EXISTS citext;

-- Enums ----------------------------------------------------------------------

CREATE TYPE user_role AS ENUM ('admin', 'user');
CREATE TYPE user_status AS ENUM ('active', 'suspended', 'pending_verification', 'deleted');
CREATE TYPE device_status AS ENUM ('active', 'paused', 'revoked');
CREATE TYPE device_os AS ENUM ('ios', 'android', 'macos', 'windows', 'linux', 'other');
CREATE TYPE token_purpose AS ENUM ('email_verify', 'password_reset');
CREATE TYPE api_token_scope AS ENUM ('read', 'read_write', 'admin');
CREATE TYPE failed_login_reason AS ENUM (
    'wrong_password', 'unknown_email', 'totp_failed',
    'account_suspended', 'account_pending_verification', 'rate_limited'
);
CREATE TYPE bucket_kind AS ENUM ('hour', 'day', 'month');

-- Users ----------------------------------------------------------------------

CREATE TABLE users (
    id UUID PRIMARY KEY,
    email CITEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role user_role NOT NULL DEFAULT 'user',
    status user_status NOT NULL DEFAULT 'pending_verification',
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    email_verified_at TIMESTAMPTZ,
    totp_secret_encrypted BYTEA,
    totp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    totp_recovery_codes_hashed TEXT[],
    monthly_byte_cap BIGINT,
    current_month_bytes BIGINT NOT NULL DEFAULT 0,
    quota_resets_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_users_status ON users(status) WHERE deleted_at IS NULL;
CREATE INDEX idx_users_role ON users(role) WHERE deleted_at IS NULL;

-- Servers --------------------------------------------------------------------

CREATE TABLE servers (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    region TEXT NOT NULL,
    endpoint_host TEXT NOT NULL,
    endpoint_port INT NOT NULL DEFAULT 51820,
    public_key TEXT NOT NULL,
    cidr CIDR NOT NULL,
    dns_servers INET[] NOT NULL DEFAULT ARRAY['1.1.1.1'::INET, '1.0.0.1'::INET],
    mtu INT NOT NULL DEFAULT 1420,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Devices --------------------------------------------------------------------

CREATE TABLE devices (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    server_id UUID NOT NULL REFERENCES servers(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    os device_os NOT NULL DEFAULT 'other',
    public_key TEXT NOT NULL UNIQUE,
    preshared_key_encrypted BYTEA,
    allocated_ip INET NOT NULL,
    status device_status NOT NULL DEFAULT 'active',
    dns_names TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    allowed_ips_override TEXT[],
    dns_override INET[],
    last_handshake_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (server_id, allocated_ip)
);
CREATE INDEX idx_devices_user ON devices(user_id) WHERE status <> 'revoked';
CREATE INDEX idx_devices_server_status ON devices(server_id, status);
-- DNS name uniqueness across the deployment is enforced in the app layer for
-- 1A. A side-table `device_dns_names` with a UNIQUE constraint will replace
-- the array column in 1B for proper SQL-level enforcement.

-- Sessions -------------------------------------------------------------------

CREATE TABLE sessions (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    refresh_token_hash TEXT NOT NULL UNIQUE,
    user_agent_hash TEXT,
    ip_prefix INET,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ
);
CREATE INDEX idx_sessions_user_active ON sessions(user_id) WHERE revoked_at IS NULL;
CREATE INDEX idx_sessions_expires ON sessions(expires_at) WHERE revoked_at IS NULL;

-- Verification tokens (email verify + password reset) ------------------------

CREATE TABLE verification_tokens (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    purpose token_purpose NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_vtoken_user_purpose
    ON verification_tokens(user_id, purpose)
    WHERE consumed_at IS NULL;

-- Audit logs (admin actions) --------------------------------------------------

CREATE TABLE audit_logs (
    id BIGSERIAL PRIMARY KEY,
    actor_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    target_type TEXT,
    target_id UUID,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    ip_prefix INET,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_audit_created ON audit_logs(created_at DESC);
CREATE INDEX idx_audit_actor ON audit_logs(actor_user_id, created_at DESC);
CREATE INDEX idx_audit_target ON audit_logs(target_type, target_id);

-- API tokens ------------------------------------------------------------------

CREATE TABLE api_tokens (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    scope api_token_scope NOT NULL DEFAULT 'read',
    last_used_at TIMESTAMPTZ,
    last_used_ip_prefix INET,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_api_tokens_user ON api_tokens(user_id) WHERE revoked_at IS NULL;

-- Failed logins ---------------------------------------------------------------

CREATE TABLE failed_logins (
    id BIGSERIAL PRIMARY KEY,
    email_attempted CITEXT,
    ip_prefix INET,
    user_agent_hash TEXT,
    reason failed_login_reason NOT NULL,
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_failed_logins_recent ON failed_logins(attempted_at DESC);
CREATE INDEX idx_failed_logins_email ON failed_logins(email_attempted, attempted_at DESC);
CREATE INDEX idx_failed_logins_ip ON failed_logins(ip_prefix, attempted_at DESC);

-- Bandwidth samples (raw, partitioned monthly, retained 7d) -------------------
-- Stores DELTAS, not cumulative counters. The poller does delta computation
-- in-memory and inserts deltas here for aggregation later.

CREATE TABLE bandwidth_samples (
    device_id UUID NOT NULL,
    sampled_at TIMESTAMPTZ NOT NULL,
    rx_bytes BIGINT NOT NULL,
    tx_bytes BIGINT NOT NULL,
    PRIMARY KEY (device_id, sampled_at)
) PARTITION BY RANGE (sampled_at);
CREATE INDEX idx_samples_time ON bandwidth_samples(sampled_at);

-- Bootstrap initial monthly partitions; the retention/maintenance job creates
-- subsequent ones. Range is inclusive lower, exclusive upper.
CREATE TABLE bandwidth_samples_2026_05 PARTITION OF bandwidth_samples
    FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE bandwidth_samples_2026_06 PARTITION OF bandwidth_samples
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE bandwidth_samples_2026_07 PARTITION OF bandwidth_samples
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');

-- Bandwidth aggregates (hour/day/month buckets) -------------------------------

CREATE TABLE bandwidth_aggregates (
    device_id UUID NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bucket bucket_kind NOT NULL,
    bucket_start TIMESTAMPTZ NOT NULL,
    rx_bytes BIGINT NOT NULL,
    tx_bytes BIGINT NOT NULL,
    sample_count INT NOT NULL,
    PRIMARY KEY (device_id, bucket, bucket_start)
);
CREATE INDEX idx_agg_user_bucket
    ON bandwidth_aggregates(user_id, bucket, bucket_start DESC);

-- App settings (single row, holds runtime toggles) ----------------------------

CREATE TABLE app_settings (
    id INT PRIMARY KEY DEFAULT 1,
    maintenance_mode BOOLEAN NOT NULL DEFAULT FALSE,
    maintenance_message TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (id = 1)
);
INSERT INTO app_settings (id) VALUES (1);

-- updated_at triggers ---------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER app_settings_updated_at BEFORE UPDATE ON app_settings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
