//! Per-peer DNS via a hosts-file resolver.
//!
//! Writes a hosts file like `/etc/dnsmasq.d/zerovpn-peers.conf` with
//! standard hosts-file lines derived from `devices.dns_names`.
//! Query logging now comes from the resolver container rather than the
//! writer; it reloads the file on a short interval.

use std::{net::IpAddr, path::Path};

use once_cell::sync::Lazy;
use regex::Regex;
use thiserror::Error;
use tokio::{fs, io::AsyncWriteExt};
use tracing::info;

// Multi-label hostnames are permitted under `.vpn.local` so user-supplied
// formats like `<device>.<user>.vpn.local` round-trip. Each label is the
// same 1–30 char alphanumeric-with-hyphens shape as before; the optional
// repeated group lets additional labels stack to the left.
static HOSTNAME_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(
        r"^[a-z0-9]([a-z0-9-]{0,28}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,28}[a-z0-9])?)*\.vpn\.local$",
    )
    .unwrap()
});

#[derive(Debug, Error)]
pub enum DnsError {
    #[error("invalid hostname: {0}")]
    InvalidHostname(String),
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
}

#[derive(Debug, Clone)]
pub struct PeerDnsEntry {
    pub name: String,
    pub ip: IpAddr,
}

pub fn validate_hostname(name: &str) -> Result<(), DnsError> {
    if !HOSTNAME_RE.is_match(name) {
        return Err(DnsError::InvalidHostname(name.to_string()));
    }
    Ok(())
}

/// Atomically write the hosts file (temp + rename).
pub async fn write_hosts_file(
    path: &Path,
    entries: &[PeerDnsEntry],
) -> Result<(), DnsError> {
    let tmp = path.with_extension("tmp");
    let mut f = fs::File::create(&tmp).await?;
    let mut out = String::with_capacity(entries.len() * 64);
    out.push_str("# Generated by ZeroVPN. Do not edit by hand.\n");
    for e in entries {
        out.push_str(&format!("{} {}\n", e.ip, e.name));
    }
    f.write_all(out.as_bytes()).await?;
    f.sync_all().await?;
    drop(f);
    // CoreDNS reads this file over a shared volume as a NON-root user. The API
    // writes it as root and `File::create` honours the process umask (often
    // 077 → mode 600), which leaves the file unreadable to CoreDNS — its
    // `hosts` plugin then silently loads nothing and every *.vpn.local query
    // NXDOMAINs. Force world-readable (0644) so the resolver can read it. The
    // file holds only <vpn-ip> <hostname> mappings, no secrets.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&tmp, std::fs::Permissions::from_mode(0o644)).await?;
    }
    fs::rename(&tmp, path).await?;
    info!(path = %path.display(), entries = entries.len(), "wrote DNS hosts file");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validates_hostnames() {
        assert!(validate_hostname("laptop.vpn.local").is_ok());
        assert!(validate_hostname("my-phone.vpn.local").is_ok());
        assert!(validate_hostname("a.vpn.local").is_ok());
        // Multi-label hostnames: <device>.<user>.vpn.local
        assert!(validate_hostname("mac.bhadri.vpn.local").is_ok());
        assert!(validate_hostname("my-phone.user-1.vpn.local").is_ok());
        assert!(validate_hostname("LAPTOP.vpn.local").is_err());
        assert!(validate_hostname("-bad.vpn.local").is_err());
        assert!(validate_hostname("bad-.vpn.local").is_err());
        assert!(validate_hostname("laptop.example.com").is_err());
        // Empty label rejected (consecutive dots)
        assert!(validate_hostname("a..b.vpn.local").is_err());
        // Label can't start with hyphen even in a middle segment.
        assert!(validate_hostname("mac.-bad.vpn.local").is_err());
    }
}
