//! Per-peer DNS via dnsmasq.
//!
//! Writes a hosts file like `/etc/dnsmasq.d/zerovpn-peers.conf` with
//! `address=/<name>/<ip>` entries derived from `devices.dns_names`.
//! After writing, signals dnsmasq via SIGHUP (or relies on `--addn-hosts`
//! re-read on next query).

use std::{net::IpAddr, path::Path};

use once_cell::sync::Lazy;
use regex::Regex;
use thiserror::Error;
use tokio::{fs, io::AsyncWriteExt};
use tracing::info;

static HOSTNAME_RE: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"^[a-z0-9]([a-z0-9-]{0,28}[a-z0-9])?\.vpn\.local$").unwrap()
});

#[derive(Debug, Error)]
pub enum DnsError {
    #[error("invalid hostname: {0}")]
    InvalidHostname(String),
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
}

#[derive(Debug, Clone)]
pub struct PeerDnsEntry {
    pub name: String,
    pub ip: IpAddr,
}

pub fn validate_hostname(name: &str) -> Result<(), DnsError> {
    if !HOSTNAME_RE.is_match(name) {
        return Err(DnsError::InvalidHostname(name.to_string()));
    }
    Ok(())
}

/// Atomically write the hosts file (temp + rename).
pub async fn write_hosts_file(
    path: &Path,
    entries: &[PeerDnsEntry],
) -> Result<(), DnsError> {
    let tmp = path.with_extension("tmp");
    let mut f = fs::File::create(&tmp).await?;
    let mut out = String::with_capacity(entries.len() * 64);
    out.push_str("# Generated by ZeroVPN. Do not edit by hand.\n");
    for e in entries {
        out.push_str(&format!("address=/{}/{}\n", e.name, e.ip));
    }
    f.write_all(out.as_bytes()).await?;
    f.sync_all().await?;
    drop(f);
    fs::rename(&tmp, path).await?;
    info!(path = %path.display(), entries = entries.len(), "wrote dnsmasq hosts file");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validates_hostnames() {
        assert!(validate_hostname("laptop.vpn.local").is_ok());
        assert!(validate_hostname("my-phone.vpn.local").is_ok());
        assert!(validate_hostname("a.vpn.local").is_ok());
        assert!(validate_hostname("LAPTOP.vpn.local").is_err());
        assert!(validate_hostname("-bad.vpn.local").is_err());
        assert!(validate_hostname("bad-.vpn.local").is_err());
        assert!(validate_hostname("laptop.example.com").is_err());
    }
}
